apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: myLocal-data
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
      # schemaFilePath: Not required since there is no OpenAPI spec
